import type { Metadata } from "next";
import "./globals.css";
import LayoutControl from "@/components/LayoutControl";
import { roboto } from "@/lib/fonts";
import AuthProvider from "@/utils/auth/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
          <LayoutControl>{children}</LayoutControl>
        </AuthProvider>
      </body>
    </html>
  );
}
