import type { Metadata } from "next";
import "./globals.css";
import { isAuth } from "@/utils/token";
import { redirect } from "next/navigation";
import { AuthWrapper } from "@/context/AuthWrapper";
import LayoutControl from "@/components/LayoutControl";
import { roboto } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const auth = isAuth;
  if (!auth) {
    redirect("/login");
  }
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthWrapper>
          <LayoutControl>{children}</LayoutControl>
        </AuthWrapper>
      </body>
    </html>
  );
}
